eventcommands = {
  "lonley":"hey, die alone",
  "what":"Learn or I will chew your eyeballs out",
  "no":"BUT WHY",
  "wtf":"lmao this asshole",
  "bruh":"bruh bruh",
  "bae":"wassup my shawty Bae",
  "stfu":"why dipstick",
  "lol":"haha a laughing loser",
  "wow":"ur stoopid",
  "yes":"r u sure",
  "lmao":"wow what a dipstick",
  "gun":"guns are dangerous",
  "nou":"get fwhucked brandon",
}
alwayscommands = {
  "heck": "Error 420: No applicable 'bad word' can satisfy. Please try again",
  "shoot": "Error 420: No applicable 'bad word' can satisfy. Please try again",
	"crap": "Error 420: No applicable 'bad word' can satisfy. Please try again",
  "Angel":"He is my best fwriend, we get icecream together!! :D",
	"Marmu":"eww a worm",
  "yes, my life":"oh, OH SHIZ",
  "yes, inside":"Same q-q",
  "Demon Cheese": "Only the best cheese possible",
  "what are you doing?":"Illigal doings don't call the police",
  "Markoth":"Alexa play Mothman",
  "The collector":"H A N D S",
  "Pure Vessel":"oh that mothertrucker",
  "Groz Mother":"He do be sleeping doe",
  "No eyes":"lel imaginge not being able to see",
  "Broken Vessel":"He do be looking like a lava lamp",
  "Xero":"Mr tentacle man",
  "Paintmaster Sheo":"r u gonna paint me like ur french girls?",
  "Massive Moss Charger (aka: the bush)":"B U S H M A N",
  "Gorb":"Micro worm butt",
  "Soul Master":"ur a wizzard harry",
  "Galien":"CRAB MEAT",
  "Dung Defender":"He yeets poopoo",
  "Nightmare King Grim":"Stoopid vampire man",
  "Winged Nosk":"My pet, miNEEE",
  "Crystal Guardian":"roCk",
  "Uumuu":"UWU   i want to die now",
  "Hive knight":"Swarm of death bees rain from above!",
  "cheese":"unholy",
	"i am b":"let me go grab the spatchula",
  "nice":"NOICE",
	"test":"I am dead inside",
	"sus":"nah u vented no cap",
  "I hate you":"Ungrateful loser",
	"ahaha":"alive, ahaha why q-q",
	"croissant":"haha a bored loser",
  "fish":"fishy sticks",
  "gobble":"gobble"
}
